### ISSUE TITLE
Work around Mojang API ratelimits

### ISSUE THREAD

**Issue by astei** [nodecraft/crafthead#23]
Even Cloudflare Workers cannot escape the 429 errors the Mojang API likes to throw up. This most likely means:

1. Find some way to set aside certain IPs for communicating to Mojang from Cloudflare
2. Develop a service to deploy as a simple container that can handle the requests for us with "enough" IPs (such as AWS Lambda, or even a few cheap VPSes)

**Comment by TibiNonEst** [comment]
I mean, there's always the option of having a fallback API like Electroid's [mojang-api](https://github.com/Electroid/mojang-api) for if requests to Mojang's API bounce. You'd probably want to talk to the host of whatever fallback about what the load on their API would be if you end up going that route.

**Comment by astei** [comment]
The problem is that Electroid’s API is hosted on… Cloudflare Workers! So this is not much better on our end.

**Comment by TibiNonEst** [comment]
Oh, yeah that makes total sense, I don't know why I didn't realize that would be an issue. Oh well...

**Comment by TibiNonEst** [comment]
Idk if there's a way to tell Cloudflare to query from a different datacenter, but if there is that might be a way of mitigating this. I don't know how this would look in practice but it's an idea.

**Comment by andreasdc** [comment]
What happens when Mojang's api can't be reached? Will I receive error or just empy/no-premium response? This is a big problem with Electroid's api.

**Comment by Cherry** [comment]
This has been mostly resolved with https://github.com/nodecraft/crafthead/pull/83. PlayerDB uses a lot of proxies to workaround this problem as best as it can.
