### ISSUE TITLE
Support for texture IDs

### ISSUE THREAD

**Issue by Vankka** [nodecraft/crafthead#25]
The ability to request a player head directly via texture id, `http://textures.minecraft.net/texture/<texture id>`, for example `http://textures.minecraft.net/texture/f4f5b52d9ad21cfa175c4bde8314be44ea0c448afe531939e1a22ed11a665c77`

### Why?

Avoiding the cache that's bound to the UUID, querying by texture id directly would result in having the right head, right after the player's skin is changed.

Or if the (*online*) UUID isn't known but the texture id is, that would avoid 2 requests (username->uuid & uuid->profile)

**Comment by astei** [comment]
Sorry for the late response on this one, I've been caught up in other stuff.

I'm happy to work on this over the holiday break.

**Comment by FN-FAL113** [comment]
Up for this, very handy
