### ISSUE TITLE
Cape Endpoint headers

### ISSUE THREAD

**Issue by bribes** [nodecraft/crafthead#58]
For the cape endpoint headers make it not respond with the x-crafthead-skin-model instead respond with a header to show the texture identifier.

**Comment by TibiNonEst** [comment]
There's also the question of whether avatars, helms, busts, etc should return the `X-Crafthead-Skin-Model` header or only the skin endpoint. My thinking when adding that header in is that, since we're already making a request to Mojang's servers and have the model, someone using the API might find it useful to not have to make an extrenous request.

**Comment by bribes** [comment]
> There's also the question of whether avatars, helms, busts, etc should return the `X-Crafthead-Skin-Model` header or only the skin endpoint. My thinking when adding that header in is that, since we're already making a request to Mojang's servers and have the model, someone using the API might find it useful to not have to make an extrenous request.

I think you should only have the header if the render is effected by the model.

**Comment by TibiNonEst** [comment]
> I think you should only have the header if the render is effected by the model.

That would mean only body and bust renders. Do you think skin requests should return the header as well? It could be useful to someone using the service. But yes I agree that renders not affected do not need the header.

**Comment by bribes** [comment]
> > I think you should only have the header if the render is effected by the model.
> 
> That would mean only body and bust renders. Do you think skin requests should return the header as well? It could be useful to someone using the service. But yes I agree that renders not affected do not need the header.

maybe
