### ISSUE TITLE
Seemingly random 403s

### ISSUE THREAD

**Issue by HexedHero** [nodecraft/crafthead#61]
Requesting https://crafthead.net/avatar/0c88a1d2-eb94-4175-a90f-f57db901937d/8 on Minecraft 1.19 works flawlessly however when doing the same request on 1.8 or 1.15 for example it will give
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://crafthead.net/avatar/0c88a1d2-eb94-4175-a90f-f57db901937d/8

I cannot figure out why, my only guess is that CloudFlare is set up to only accept certain protocol versions?

**Comment by Cherry** [comment]
This was likely fixed with https://github.com/nodecraft/crafthead/pull/83. Please let us know if you continue to hit this.
