### ISSUE TITLE
Worker running into HTTP 429

### ISSUE THREAD

**Issue by tycrek** [nodecraft/crafthead#68]
I noticed my site is failing to load resources, causing my users to receive an HTTP 500 (generates a pack based off the user skin). What I believe is happening is Crafthead is running into HTTP 429 (Too Many Requests) against the Mojang UUID/Username API.

One possible fix may be to use [PlayerDB.co](https://playerdb.co/) instead of the Mojang API used here 

https://github.com/astei/crafthead/blob/b00709697fea5f84337aef4bf28e095aed4a94f9/worker/services/mojang/api.ts#L101

It is also sponsored by Nodecraft, same as Crafthead ;)

**Comment by tycrek** [comment]
Agh. Nevermind, a lookup of myself was immediately ratelimited by Mojang through PlayerDB. Very odd.

**Comment by andreasdc** [comment]
PlayerDB also returns
`{"message":"Mojang has rate limited this request.","code":"minecraft.rate_limited","data":{},"success":false,"error":true}`
@astei can you check if your repo doesn't generate too much movement? All cloudflare workers are getting rate limitted since some time.

**Comment by andreasdc** [comment]
Sounds cool, it's good to find new perspectives. Nowadays all workers are getting rate limited from mojang globally at the same time, it was non stop for almost 24 hours, maybe you see bigger movement or something like that.

**Comment by Cherry** [comment]
We've implemented a solution on PlayerDB that effectively uses some servers outside of Cloudflare to fetch profiles when running into 429. That might be a good solution here now.

**Comment by andreasdc** [comment]
Last time I checked PlayerDB had rate limits too when cloudflare was down.

**Comment by Cherry** [comment]
> Last time I checked PlayerDB had rate limits too

Yep, this was a recent change we made before the holidays to workaround the increasing number of 429s we were seeing from Mojang.

**Comment by andreasdc** [comment]
What do you mean? I'm saying that PlayerDB was rate limited from mojang when cf was down.

**Comment by ShayBox** [comment]
What's the current cache strategy? I'm getting 429 on stuff that was fetched earlier and should be cached, or at least fallback to cached if the request is rate-limited.

Two strategies I can see:  
1. Keep all profiles cached and only fetch/update on request if it's older than X
2. Keep all profiles cached and separate fetching/updating into a continuous background task that only fetches the most outdated profiles first and/or prioritizing more requested profiles.

**Comment by tycrek** [comment]
I don't have a direct alternative to Crafthead's utility routes, but I do have an alternative UUID/skin lookup service for Mojang's API: https://github.com/tycrek/mulv

I'm hosting it via [Vercel Serverless Functions](https://vercel.com/docs/concepts/functions/serverless-functions) on https://mulv.tycrek.dev **but please consider hosting yourself** as I'm only on the free tier and need it for my own uses as well.

So far in my testing I haven't hit any `HTTP 429` on Mojang's API, but you never know what'll happen.

**Comment by mja00** [comment]
This should now be fixed with the latest change. We now go through PlayerDB to grab profile information. Feel free to open up a new issue if you run into issues.
