### ISSUE TITLE
Public instance: 500 Internal Server Error 

### ISSUE THREAD

**Issue by Packsolite** [nodecraft/crafthead#79]
The official public instance (crafthead.net) sometimes returns a "500 Internal Server Error". I noticed this after integrating the official api on my personal website. 

![image](https://github.com/nodecraft/crafthead/assets/102829507/5551fd9e-71e8-49cd-9469-b2648147c568)

Refreshing the page / sending the same request again usually fixes the issue temporarily.

Cloudflare's Report-To Response: ```
{"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=sF%2BbbY2U3ii%2BhDLsi5vP%2FvLl80Jog3N5DJgSmh%2BrgCQZZMYgBlbFlcnCXevwu4wIMB3gsfxLcy3tMl%2F7E1decucMz%2B9316vTv1iP4NrJNWGO6BRm3uKS3FY56PtWFxSsl6J3UIoGJalNoE7N"}],"group":"cf-nel","max_age":604800}```

**Comment by Cherry** [comment]
Thanks for the report! Did you happen to catch the full response body, and/or headers? I suspect this is related to https://github.com/nodecraft/crafthead/issues/68, with other errors that aren't being caught correctly.

**Comment by Packsolite** [comment]
> Did you happen to catch the full response body, and/or headers?
Response body is empty. Here are the headers:
```Request URL: https://crafthead.net/avatar/2e33faaf-dddb-4d3d-bb47-ab3f6eb6e1e0
Request Method: GET
Status Code: 500 Internal Server Error
Remote Address: [2606:4700:3033::ac43:dce1]:443
Referrer Policy: strict-origin-when-cross-origin

Response-Headers:
Alt-Svc: h3=":443"; ma=86400
Cf-Ray: 838a56330f6cca9d-HAM
Content-Length: 62
Content-Type: text/plain;charset=UTF-8
Date: Wed, 20 Dec 2023 19:36:53 GMT
Nel: {"success_fraction":0,"report_to":"cf-nel","max_age":604800}
Report-To: {"endpoints":[{"url":"https:\/\/a.nel.cloudflare.com\/report\/v3?s=5i4IgRmk0P6ShKpD9Ns%2BNAgwK5c4m9VoUqrCnkuBOoqQZ6OC6AuAsPM%2BbkQX5Y37Nf5tCkQyR7YiujJVF%2FRlINkiu2mFd%2F%2Fa%2BXKwO9LAKS4HbOrwlKiXKQ9hGqd0cnJiKn7pCiDLrPrU2Zdt"}],"group":"cf-nel","max_age":604800}
Server: cloudflare
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
Vary: Accept-Encoding
X-Content-Type-Options: nosniff

Request-Headers:
:authority: crafthead.net
:method: GET
:path: /avatar/2e33faaf-dddb-4d3d-bb47-ab3f6eb6e1e0
:scheme: https
Accept: image/avif,image/webp,image/apng,image/svg+xml,image/*,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language:
ja,de-DE;q=0.9,de;q=0.8,en-US;q=0.7,en;q=0.6
Referer: https://chatlog.smashmc.eu/
Sec-Ch-Ua: "Not_A Brand";v="8", "Chromium";v="120", "Google Chrome";v="120"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "Windows"
Sec-Fetch-Dest: image
Sec-Fetch-Mode: no-cors
Sec-Fetch-Site: cross-site
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36```

**Comment by andreasdc** [comment]
I notice it too. It is coming from PlayerDB too I think. 
![image](https://github.com/nodecraft/crafthead/assets/82218780/20672168-c923-4ce8-90b7-b443a8fdfb5b)
![image](https://github.com/nodecraft/crafthead/assets/82218780/888d13a5-ef1e-4d34-9521-5c1e4237cf37)
