### ISSUE TITLE
Profile endpoint giving 403

### ISSUE THREAD

**Issue by powercasgamer** [nodecraft/crafthead#82]
Having some issues using the profile endpoints

https://crafthead.net/profile/powercas_gamer - Does not work, gives `Error: Unable to lookup UUID for username, http status 403`
https://crafthead.net/profile/ea3ff55d-f4bc-4fab-a6ae-d809d0849f95 - Works, gives the profile in json (likely cached?)

https://crafthead.net/profile/688eecfc-67cd-489a-8ace-2bc3ecf04614 - Does not work, gives `Error: Unable to retrieve profile from Mojang, http status 403`
https://crafthead.net/profile/Eytril - Does not work, gives `Error: Unable to lookup UUID for username, http status 403`

**Comment by Cherry** [comment]
Sorry for the issues here, we've noticed this internally too and are looking into it. Expect some updates soon.
